#version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: career-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpw
    ports:
      - "3307:3306"   # 내 컴퓨터 3307 → 컨테이너 3306
    volumes:
      - ./db/mysql-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
