FROM node:20-alpine

WORKDIR /app

# package.json만 복사
COPY package*.json ./

# 프로덕션용 패키지만 설치
RUN npm install --only=production

# 소스코드 전체 복사
COPY . .

# Production 환경
ENV NODE_ENV=production

EXPOSE 4000

CMD ["node", "src/server.js"]
