name: Backend test

on:
  push:
    branches: [ Develop]
  pull_request:
    branches: [ Develop ]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".gitignore"

permissions:
  contents: read
  pull-requests: write

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4   # 레포지토리 코드 다운로드

      # secret 환경변수 설정
      - name: Create backend .env from secret
        run: |
          mkdir -p backend
          echo "${{ secrets.BACKEND_ENV }}" > backend/.env
      # 환경변수 설정 확인
      - name: Print env test (debug)
        run: |
          echo "DB_HOST=$DB_HOST"
          echo "DB_USER=$DB_USER"
          
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose   # 테스트용 DB 실행에 필요

      - name: Start CI Docker Compose
        run: docker-compose -f docker/docker-compose.ci.yml up -d   # MySQL 컨테이너 실행

      - name: Wait For MySQL
        run: |   # DB 준비될 때까지 대기
          for i in {1..30}; do
            nc -z localhost 3307 && echo "MySQL is ready!" && exit 0
            echo "Waiting for MySQL..."
            sleep 2
          done
          exit 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20   # backend 실행 환경 맞추기

      - name: Install Dependencies
        working-directory: backend
        run: npm ci   # 의존성 설치

      - name: Run Unit Tests
        working-directory: backend
        run: npm test   # Jest 단위 테스트

      - name: Run Integration Tests
        working-directory: backend
        run: npm run test:integration   # API 통합 테스트

      - name: Generate Coverage Report
        working-directory: backend
        run: npm test -- --coverage   # 코드 커버리지 생성

      - name: Stop Docker Services
        run: docker-compose -f docker/docker-compose.ci.yml down   # 테스트 후 컨테이너 종료
